name: Top GitHub Users

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  release:
    name: Github Active Users
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CUSTOM_TOKEN }}

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.0

      - name: Top Github Users Action
        uses: gayanvoice/top-github-users-action@master
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
